### ISSUE TITLE
Can you update this for 1.5?

### ISSUE THREAD

**Issue by ahundt** [davidmoten/flatbuffers#1]
Any chance of updating the jar to flatbuffers 1.5?
https://github.com/google/flatbuffers/releases/tag/v1.5.0

**Comment by davidmoten** [comment]
sure, I'll have a look at it now.

**Comment by davidmoten** [comment]
[1.5.0.1](http://search.maven.org/#artifactdetails%7Ccom.github.davidmoten%7Cflatbuffers-java%7C1.5.0.1%7Cjar) deployed to Maven Central, give it a spin, passes tests so should work.

**Comment by davidmoten** [comment]
Encountered GLIBCXX-3-4-21 not found error on Travis. I built linux binaries on ubuntu 16.04 with gcc 5.4 which is not required so have rebuilt binaries on ubuntu 14.04 image (gcc 4.8) and tests now pass on Travis. Will release 1.5.0.2 soon.

**Comment by ahundt** [comment]
Awesome, thanks!

**Comment by davidmoten** [comment]
1.5.0.2 is out

**Comment by davidmoten** [comment]
1.6.0.1 is on Maven Central (because 1.6 has just been released)
