### ISSUE TITLE
flatbuffers-java in version 1.12.0.1 is not availabile at mvn repository

### ISSUE THREAD

**Issue by rkarczmarczyk** [davidmoten/flatbuffers#10]
flatbuffers-java in version 1.12.0.1 is not availabile at mvn repository
https://mvnrepository.com/artifact/com.github.davidmoten/flatbuffers-java
![image](https://user-images.githubusercontent.com/7958674/83031723-36b89a00-a035-11ea-91a5-10678729277e.png)

**Comment by davidmoten** [comment]
Yep that's right because google have started publishing the java classes to Maven Central. This is documented in the README.md of this project:

```xml
<dependency>
    <groupId>com.google.flatbuffers</groupId>
    <artifactId>flatbuffers-java</artifactId>
    <version>1.12.0</version>
</dependency>
```

**Comment by rkarczmarczyk** [comment]
Ok, thanks for information and really sorry for "fake" issue.
