### ISSUE TITLE
Version 1.6.0.1: Java library "flatbuffers-java" seems to be outdated. flatc generated Java sources can not be compiled against java-lib.

### ISSUE THREAD

**Issue by StefanKiendl** [davidmoten/flatbuffers#2]
Version 1.6.0.1:
Java library "flatbuffers-java" seems to be outdated. flatc generated Java sources can not be compiled against java-lib.

For
`
table HMap {
    key: string(key);
    val: string;
}

table Message {
   a: string;
   b: string;
   ttl: ulong;
   head: [HMap];
   payload: [byte];
}
`
I get problems in the generated HMap class that methods "protected static int __offset(int vtable_offset, int offset, ByteBuffer bb)" and "protected static int __indirect(int offset, ByteBuffer bb)" from Table class are missing.

In google original code
https://github.com/google/flatbuffers/blob/master/java/com/google/flatbuffers/Table.java
both methods are there.

Further a referenced "Table.UTF8_CHARSET.get()" in the generated HMap is not found.

I'm not sure if this is a problem in your library. Maybe it is also there in googles variant. At least the last problem seems to be a general one.

**Comment by davidmoten** [comment]
Thanks for the report! Yep I need to have as part of my notes for release builds to copy the relevant classes over. From the dates on the affected classes I think I'll need to rerelease the 1.5 lib as well. I'll  fix sometime  today.

**Comment by davidmoten** [comment]
I've fixed this and released 1.6.0.2 to Maven Central (usually takes 10mins from now to be available). Let me know if there's any more problem.

**Comment by davidmoten** [comment]
I've also fixed the artifact for the 1.5 release. That's available on Maven Central (1.5.0.3) now.

I checked the 1.4 release and it was complete already.

**Comment by StefanKiendl** [comment]
Works like a charm for 1.6 with the new version 1.6.0.2. Many thanks, also for the quick reaction and fix!
