### ISSUE TITLE
The  version of the 'flatc.exe' is incorrect.

### ISSUE THREAD

**Issue by vovgou** [davidmoten/flatbuffers#23]
![image](https://user-images.githubusercontent.com/2171221/163308585-836aa50a-af74-44ca-b334-7417cf4d25d1.png)

On the windows platform, I use the flatbuffers-compiler plugin to generate java code, it always uses the 1.12.0 version of flatc.exe, how do I configure it to use the 2.0.0 flatc.exe.Because the flatc.zip in the image above will not be automatically decompressed, so always use the 1.12.0 version of flatc.exe

**Comment by davidmoten** [comment]
thanks, I'll have a look. I suspect the zip shouldn't be there, I should have uncompressed and overwritten flatc.exe. I'll fix.

**Comment by davidmoten** [comment]
righto, there were some problems with both the windows and osx artifacts, sorry about that. I've fixed that with version 2.3.0.2 which is on Maven Central now. Please try it out.

**Comment by vovgou** [comment]
> 
yes, it worked, thanks.

**Comment by davidmoten** [comment]
great, thanks for the report.
