### ISSUE TITLE
1.7 binary for osx

### ISSUE THREAD

**Issue by davidmoten** [davidmoten/flatbuffers#4]
@frew Can you contribute osx binary for the 1.7 release please?

**Comment by Sachinbihade** [comment]
@davidmoten, while trying to run on MAC OS, getting below error

_target/bin/flatc: cannot execute binary file
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.926 s
[INFO] Finished at: 2021-06-15T13:55:37-07:00_

Any idea about this?
